ERROR - 2024-03-07 19:05:38 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'u954703204_donaji'@'localhost' (using password: YES) in C:\laragon\www\cine\system\Database\MySQLi\Connection.php:185

Stack trace:
#0 C:\laragon\www\cine\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', 'u954703204_dona...', 'X=Uf8TJz9~', 'u954703204_cine', 3306, '', 0)
#1 C:\laragon\www\cine\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\laragon\www\cine\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\laragon\www\cine\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\laragon\www\cine\system\Model.php(270): CodeIgniter\Database\BaseBuilder->get()
#5 C:\laragon\www\cine\system\BaseModel.php(676): CodeIgniter\Model->doFirst()
#6 C:\laragon\www\cine\app\Controllers\Login.php(19): CodeIgniter\BaseModel->first()
#7 C:\laragon\www\cine\system\CodeIgniter.php(941): App\Controllers\Login->loggeo()
#8 C:\laragon\www\cine\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#9 C:\laragon\www\cine\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\laragon\www\cine\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\laragon\www\cine\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\laragon\www\cine\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\laragon\www\cine\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\laragon\www\cine\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\laragon\www\cine\system\Model.php(270): CodeIgniter\Database\BaseBuilder->get()
#4 C:\laragon\www\cine\system\BaseModel.php(676): CodeIgniter\Model->doFirst()
#5 C:\laragon\www\cine\app\Controllers\Login.php(19): CodeIgniter\BaseModel->first()
#6 C:\laragon\www\cine\system\CodeIgniter.php(941): App\Controllers\Login->loggeo()
#7 C:\laragon\www\cine\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#8 C:\laragon\www\cine\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\laragon\www\cine\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}

CRITICAL - 2024-03-07 19:05:38 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.

Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `usuarios`
WHERE `nombre_usuario` = :nombre_usuario:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(270): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(676): CodeIgniter\Model->doFirst()
 5 APPPATH\Controllers\Login.php(19): CodeIgniter\BaseModel->first()
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Login->loggeo()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()

ERROR - 2024-03-07 19:05:58 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'u954703204_donaji'@'localhost' (using password: YES) in C:\laragon\www\cine\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\laragon\www\cine\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', 'u954703204_dona...', 'X=Uf8TJz9~', 'u954703204_cine', 3306, '', 0)

#1 C:\laragon\www\cine\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\laragon\www\cine\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\laragon\www\cine\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\laragon\www\cine\system\Model.php(270): CodeIgniter\Database\BaseBuilder->get()
#5 C:\laragon\www\cine\system\BaseModel.php(676): CodeIgniter\Model->doFirst()
#6 C:\laragon\www\cine\app\Controllers\Login.php(19): CodeIgniter\BaseModel->first()
#7 C:\laragon\www\cine\system\CodeIgniter.php(941): App\Controllers\Login->loggeo()
#8 C:\laragon\www\cine\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#9 C:\laragon\www\cine\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\laragon\www\cine\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\laragon\www\cine\system\Database\MySQLi\Connection.php:229

Stack trace:
#0 C:\laragon\www\cine\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\laragon\www\cine\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\laragon\www\cine\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\laragon\www\cine\system\Model.php(270): CodeIgniter\Database\BaseBuilder->get()
#4 C:\laragon\www\cine\system\BaseModel.php(676): CodeIgniter\Model->doFirst()
#5 C:\laragon\www\cine\app\Controllers\Login.php(19): CodeIgniter\BaseModel->first()
#6 C:\laragon\www\cine\system\CodeIgniter.php(941): App\Controllers\Login->loggeo()
#7 C:\laragon\www\cine\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#8 C:\laragon\www\cine\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\laragon\www\cine\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}

CRITICAL - 2024-03-07 19:05:58 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)

in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `usuarios`
WHERE `nombre_usuario` = :nombre_usuario:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(270): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(676): CodeIgniter\Model->doFirst()
 5 APPPATH\Controllers\Login.php(19): CodeIgniter\BaseModel->first()
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Login->loggeo()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()

ERROR - 2024-03-07 19:07:41 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'u954703204_donaji'@'localhost' (using password: YES) in C:\laragon\www\cine\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\laragon\www\cine\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', 'u954703204_dona...', 'X=Uf8TJz9~', 'u954703204_cine', 3306, '', 0)

#1 C:\laragon\www\cine\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\laragon\www\cine\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\laragon\www\cine\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\laragon\www\cine\system\Model.php(270): CodeIgniter\Database\BaseBuilder->get()
#5 C:\laragon\www\cine\system\BaseModel.php(676): CodeIgniter\Model->doFirst()
#6 C:\laragon\www\cine\app\Controllers\Login.php(19): CodeIgniter\BaseModel->first()
#7 C:\laragon\www\cine\system\CodeIgniter.php(941): App\Controllers\Login->loggeo()
#8 C:\laragon\www\cine\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#9 C:\laragon\www\cine\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\laragon\www\cine\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\laragon\www\cine\system\Database\MySQLi\Connection.php:229

Stack trace:
#0 C:\laragon\www\cine\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\laragon\www\cine\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\laragon\www\cine\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\laragon\www\cine\system\Model.php(270): CodeIgniter\Database\BaseBuilder->get()
#4 C:\laragon\www\cine\system\BaseModel.php(676): CodeIgniter\Model->doFirst()
#5 C:\laragon\www\cine\app\Controllers\Login.php(19): CodeIgniter\BaseModel->first()
#6 C:\laragon\www\cine\system\CodeIgniter.php(941): App\Controllers\Login->loggeo()
#7 C:\laragon\www\cine\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#8 C:\laragon\www\cine\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\laragon\www\cine\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}

CRITICAL - 2024-03-07 19:07:41 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)

in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `usuarios`
WHERE `nombre_usuario` = :nombre_usuario:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(270): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(676): CodeIgniter\Model->doFirst()
 5 APPPATH\Controllers\Login.php(19): CodeIgniter\BaseModel->first()
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Login->loggeo()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()

ERROR - 2024-03-07 19:07:46 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'u954703204_donaji'@'localhost' (using password: YES) in C:\laragon\www\cine\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\laragon\www\cine\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', 'u954703204_dona...', 'X=Uf8TJz9~', 'u954703204_cine', 3306, '', 0)

#1 C:\laragon\www\cine\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\laragon\www\cine\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\laragon\www\cine\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\laragon\www\cine\system\Model.php(270): CodeIgniter\Database\BaseBuilder->get()
#5 C:\laragon\www\cine\system\BaseModel.php(676): CodeIgniter\Model->doFirst()
#6 C:\laragon\www\cine\app\Controllers\Login.php(19): CodeIgniter\BaseModel->first()
#7 C:\laragon\www\cine\system\CodeIgniter.php(941): App\Controllers\Login->loggeo()
#8 C:\laragon\www\cine\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#9 C:\laragon\www\cine\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\laragon\www\cine\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\laragon\www\cine\system\Database\MySQLi\Connection.php:229

Stack trace:
#0 C:\laragon\www\cine\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\laragon\www\cine\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\laragon\www\cine\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\laragon\www\cine\system\Model.php(270): CodeIgniter\Database\BaseBuilder->get()
#4 C:\laragon\www\cine\system\BaseModel.php(676): CodeIgniter\Model->doFirst()
#5 C:\laragon\www\cine\app\Controllers\Login.php(19): CodeIgniter\BaseModel->first()
#6 C:\laragon\www\cine\system\CodeIgniter.php(941): App\Controllers\Login->loggeo()
#7 C:\laragon\www\cine\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#8 C:\laragon\www\cine\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\laragon\www\cine\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}

CRITICAL - 2024-03-07 19:07:46 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)

in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `usuarios`
WHERE `nombre_usuario` = :nombre_usuario:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(270): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(676): CodeIgniter\Model->doFirst()
 5 APPPATH\Controllers\Login.php(19): CodeIgniter\BaseModel->first()
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Login->loggeo()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-03-07 19:14:06 --> Error connecting to the database: ErrorException: mysqli::real_connect(): php_network_getaddresses: getaddrinfo for mysql.hostinger.com failed: Host desconocido.  in C:\laragon\www\cine\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mysqli::real_co...', 'C:\\laragon\\www\\...', 185)
#1 C:\laragon\www\cine\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('mysql.hostinger...', 'u954703204_dona...', 'X=Uf8TJz9~', 'u954703204_cine', 3306, '', 0)

#2 C:\laragon\www\cine\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#3 C:\laragon\www\cine\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\laragon\www\cine\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#5 C:\laragon\www\cine\system\Model.php(270): CodeIgniter\Database\BaseBuilder->get()
#6 C:\laragon\www\cine\system\BaseModel.php(676): CodeIgniter\Model->doFirst()
#7 C:\laragon\www\cine\app\Controllers\Login.php(19): CodeIgniter\BaseModel->first()
#8 C:\laragon\www\cine\system\CodeIgniter.php(941): App\Controllers\Login->loggeo()
#9 C:\laragon\www\cine\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#10 C:\laragon\www\cine\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\laragon\www\cine\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 {main}

Next mysqli_sql_exception: php_network_getaddresses: getaddrinfo for mysql.hostinger.com failed: Host desconocido.  in C:\laragon\www\cine\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\laragon\www\cine\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('mysql.hostinger...', 'u954703204_dona...', 'X=Uf8TJz9~', 'u954703204_cine', 3306, '', 0)

#1 C:\laragon\www\cine\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\laragon\www\cine\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\laragon\www\cine\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\laragon\www\cine\system\Model.php(270): CodeIgniter\Database\BaseBuilder->get()
#5 C:\laragon\www\cine\system\BaseModel.php(676): CodeIgniter\Model->doFirst()
#6 C:\laragon\www\cine\app\Controllers\Login.php(19): CodeIgniter\BaseModel->first()
#7 C:\laragon\www\cine\system\CodeIgniter.php(941): App\Controllers\Login->loggeo()
#8 C:\laragon\www\cine\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#9 C:\laragon\www\cine\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\laragon\www\cine\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: php_network_getaddresses: getaddrinfo for mysql.hostinger.com failed: Host desconocido.  in C:\laragon\www\cine\system\Database\MySQLi\Connection.php:229

Stack trace:
#0 C:\laragon\www\cine\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\laragon\www\cine\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\laragon\www\cine\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\laragon\www\cine\system\Model.php(270): CodeIgniter\Database\BaseBuilder->get()
#4 C:\laragon\www\cine\system\BaseModel.php(676): CodeIgniter\Model->doFirst()
#5 C:\laragon\www\cine\app\Controllers\Login.php(19): CodeIgniter\BaseModel->first()
#6 C:\laragon\www\cine\system\CodeIgniter.php(941): App\Controllers\Login->loggeo()
#7 C:\laragon\www\cine\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
#8 C:\laragon\www\cine\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\laragon\www\cine\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}

CRITICAL - 2024-03-07 19:14:06 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: php_network_getaddresses: getaddrinfo for mysql.hostinger.com failed: Host desconocido. 

in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `usuarios`
WHERE `nombre_usuario` = :nombre_usuario:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(270): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(676): CodeIgniter\Model->doFirst()
 5 APPPATH\Controllers\Login.php(19): CodeIgniter\BaseModel->first()
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Login->loggeo()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Login))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
 
 ERROR - 2024-03-07 19:45:57 --> Error connecting to the database: ErrorException: mysqli::real_connect(): php_network_getaddresses: getaddrinfo for srv867.hstgr.io failed: Host desconocido.  in C:\laragon\www\cine\system\Database\MySQLi\Connection.php:185

Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mysqli::real_co...', 'C:\\laragon\\www\\...', 185)
#1 C:\laragon\www\cine\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('srv867.hstgr.io', 'u954703204_dona...', 'X=Uf8TJz9~', 'u954703204_cine', 3306, '', 0)
#2 C:\laragon\www\cine\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#3 C:\laragon\www\cine\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\laragon\www\cine\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#5 C:\laragon\www\cine\system\Model.php(242): CodeIgniter\Database\BaseBuilder->get()
#6 C:\laragon\www\cine\system\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
#7 C:\laragon\www\cine\app\Controllers\Usuarios.php(32): CodeIgniter\BaseModel->findAll()
#8 C:\laragon\www\cine\system\CodeIgniter.php(941): App\Controllers\Usuarios->usuarios_view()
#9 C:\laragon\www\cine\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuarios))
#10 C:\laragon\www\cine\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\laragon\www\cine\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 {main}

Next mysqli_sql_exception: php_network_getaddresses: getaddrinfo for srv867.hstgr.io failed: Host desconocido.  in C:\laragon\www\cine\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\laragon\www\cine\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('srv867.hstgr.io', 'u954703204_dona...', 'X=Uf8TJz9~', 'u954703204_cine', 3306, '', 0)
#1 C:\laragon\www\cine\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\laragon\www\cine\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\laragon\www\cine\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\laragon\www\cine\system\Model.php(242): CodeIgniter\Database\BaseBuilder->get()
#5 C:\laragon\www\cine\system\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\laragon\www\cine\app\Controllers\Usuarios.php(32): CodeIgniter\BaseModel->findAll()
#7 C:\laragon\www\cine\system\CodeIgniter.php(941): App\Controllers\Usuarios->usuarios_view()
#8 C:\laragon\www\cine\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuarios))
#9 C:\laragon\www\cine\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\laragon\www\cine\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: php_network_getaddresses: getaddrinfo for srv867.hstgr.io failed: Host desconocido.  in C:\laragon\www\cine\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\laragon\www\cine\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\laragon\www\cine\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\laragon\www\cine\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\laragon\www\cine\system\Model.php(242): CodeIgniter\Database\BaseBuilder->get()
#4 C:\laragon\www\cine\system\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\laragon\www\cine\app\Controllers\Usuarios.php(32): CodeIgniter\BaseModel->findAll()
#6 C:\laragon\www\cine\system\CodeIgniter.php(941): App\Controllers\Usuarios->usuarios_view()
#7 C:\laragon\www\cine\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuarios))
#8 C:\laragon\www\cine\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\laragon\www\cine\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}

CRITICAL - 2024-03-07 19:45:57 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.

Main connection [MySQLi]: php_network_getaddresses: getaddrinfo for srv867.hstgr.io failed: Host desconocido. 
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `usuarios`
ORDER BY `id_usuario` ASC', [], false)
 3 SYSTEMPATH\Model.php(242): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Usuarios.php(32): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Usuarios->usuarios_view()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuarios))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()

ERROR - 2024-03-07 19:46:00 --> Error connecting to the database: ErrorException: mysqli::real_connect(): php_network_getaddresses: getaddrinfo for srv867.hstgr.io failed: Host desconocido.  in C:\laragon\www\cine\system\Database\MySQLi\Connection.php:185

Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mysqli::real_co...', 'C:\\laragon\\www\\...', 185)
#1 C:\laragon\www\cine\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('srv867.hstgr.io', 'u954703204_dona...', 'X=Uf8TJz9~', 'u954703204_cine', 3306, '', 0)
#2 C:\laragon\www\cine\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#3 C:\laragon\www\cine\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\laragon\www\cine\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#5 C:\laragon\www\cine\system\Model.php(242): CodeIgniter\Database\BaseBuilder->get()
#6 C:\laragon\www\cine\system\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
#7 C:\laragon\www\cine\app\Controllers\Usuarios.php(32): CodeIgniter\BaseModel->findAll()
#8 C:\laragon\www\cine\system\CodeIgniter.php(941): App\Controllers\Usuarios->usuarios_view()
#9 C:\laragon\www\cine\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuarios))
#10 C:\laragon\www\cine\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\laragon\www\cine\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 {main}

Next mysqli_sql_exception: php_network_getaddresses: getaddrinfo for srv867.hstgr.io failed: Host desconocido.  in C:\laragon\www\cine\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\laragon\www\cine\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('srv867.hstgr.io', 'u954703204_dona...', 'X=Uf8TJz9~', 'u954703204_cine', 3306, '', 0)
#1 C:\laragon\www\cine\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\laragon\www\cine\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\laragon\www\cine\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\laragon\www\cine\system\Model.php(242): CodeIgniter\Database\BaseBuilder->get()
#5 C:\laragon\www\cine\system\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\laragon\www\cine\app\Controllers\Usuarios.php(32): CodeIgniter\BaseModel->findAll()
#7 C:\laragon\www\cine\system\CodeIgniter.php(941): App\Controllers\Usuarios->usuarios_view()
#8 C:\laragon\www\cine\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuarios))
#9 C:\laragon\www\cine\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\laragon\www\cine\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: php_network_getaddresses: getaddrinfo for srv867.hstgr.io failed: Host desconocido.  in C:\laragon\www\cine\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\laragon\www\cine\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\laragon\www\cine\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\laragon\www\cine\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\laragon\www\cine\system\Model.php(242): CodeIgniter\Database\BaseBuilder->get()
#4 C:\laragon\www\cine\system\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\laragon\www\cine\app\Controllers\Usuarios.php(32): CodeIgniter\BaseModel->findAll()
#6 C:\laragon\www\cine\system\CodeIgniter.php(941): App\Controllers\Usuarios->usuarios_view()
#7 C:\laragon\www\cine\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuarios))
#8 C:\laragon\www\cine\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\laragon\www\cine\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}

CRITICAL - 2024-03-07 19:46:00 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.

Main connection [MySQLi]: php_network_getaddresses: getaddrinfo for srv867.hstgr.io failed: Host desconocido. 
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `usuarios`
ORDER BY `id_usuario` ASC', [], false)
 3 SYSTEMPATH\Model.php(242): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Usuarios.php(32): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Usuarios->usuarios_view()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuarios))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()

ERROR - 2024-03-07 19:48:16 --> mysqli_sql_exception: Duplicate entry 'Tomas' for key 'unique_nombre_usuario' in C:\laragon\www\cine\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\laragon\www\cine\system\Database\MySQLi\Connection.php(306): mysqli->query('UPDATE `usuario...', 0)
#1 C:\laragon\www\cine\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `usuario...')
#2 C:\laragon\www\cine\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `usuario...')
#3 C:\laragon\www\cine\system\Database\BaseBuilder.php(2474): CodeIgniter\Database\BaseConnection->query('UPDATE `usuario...', Array, false)
#4 C:\laragon\www\cine\system\Model.php(393): CodeIgniter\Database\BaseBuilder->update()
#5 C:\laragon\www\cine\system\BaseModel.php(987): CodeIgniter\Model->doUpdate(Array, Array)
#6 C:\laragon\www\cine\system\Model.php(807): CodeIgniter\BaseModel->update(Array, Array)
#7 C:\laragon\www\cine\app\Controllers\Usuarios.php(211): CodeIgniter\Model->update('27', Array)
#8 C:\laragon\www\cine\system\CodeIgniter.php(941): App\Controllers\Usuarios->actualizar()


#9 C:\laragon\www\cine\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuarios))
#10 C:\laragon\www\cine\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\laragon\www\cine\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 {main}

CRITICAL - 2024-03-07 19:48:16 --> CodeIgniter\Database\Exceptions\DatabaseException: Duplicate entry 'Tomas' for key 'unique_nombre_usuario'
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2474): CodeIgniter\Database\BaseConnection->query('UPDATE `usuarios` SET `nombre_usuario` = :nombre_usuario:, `password` = :password:, `tipo_usuario` = :tipo_usuario:, `estado_usuario` = :estado_usuario:
WHERE `usuarios`.`id_usuario` IN :usuarios.id_usuario:', [...], false)
 2 SYSTEMPATH\Model.php(393): CodeIgniter\Database\BaseBuilder->update()
 3 SYSTEMPATH\BaseModel.php(987): CodeIgniter\Model->doUpdate([...], [...])
 4 SYSTEMPATH\Model.php(807): CodeIgniter\BaseModel->update([...], [...])
 5 APPPATH\Controllers\Usuarios.php(211): CodeIgniter\Model->update('27', [...])
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Usuarios->actualizar()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuarios))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-03-07 19:48:16 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Duplicate entry 'Tomas' for key 'unique_nombre_usuario'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `usuarios` SET `nombre_usuario` = \'Tomas\', `password` = \'GRh8eu8M1XAzUkPCvepZbzRJdEhiWjdDamZSWFQ2OEtPbnNtdmc9PQ==\', `tipo_usuario` = \'Taquillero\', `estado_usuario` = \'Activo\'
WHERE `usuarios`.`id_usuario` IN (\'27\')')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `usuarios` SET `nombre_usuario` = \'Tomas\', `password` = \'GRh8eu8M1XAzUkPCvepZbzRJdEhiWjdDamZSWFQ2OEtPbnNtdmc9PQ==\', `tipo_usuario` = \'Taquillero\', `estado_usuario` = \'Activo\'
WHERE `usuarios`.`id_usuario` IN (\'27\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2474): CodeIgniter\Database\BaseConnection->query('UPDATE `usuarios` SET `nombre_usuario` = :nombre_usuario:, `password` = :password:, `tipo_usuario` = :tipo_usuario:, `estado_usuario` = :estado_usuario:
WHERE `usuarios`.`id_usuario` IN :usuarios.id_usuario:', [...], false)
 4 SYSTEMPATH\Model.php(393): CodeIgniter\Database\BaseBuilder->update()
 5 SYSTEMPATH\BaseModel.php(987): CodeIgniter\Model->doUpdate([...], [...])
 6 SYSTEMPATH\Model.php(807): CodeIgniter\BaseModel->update([...], [...])
 7 APPPATH\Controllers\Usuarios.php(211): CodeIgniter\Model->update('27', [...])
 8 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Usuarios->actualizar()
 9 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuarios))
10 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-03-07 19:48:16 --> [Caused by] mysqli_sql_exception: Duplicate entry 'Tomas' for key 'unique_nombre_usuario'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('UPDATE `usuarios` SET `nombre_usuario` = \'Tomas\', `password` = \'GRh8eu8M1XAzUkPCvepZbzRJdEhiWjdDamZSWFQ2OEtPbnNtdmc9PQ==\', `tipo_usuario` = \'Taquillero\', `estado_usuario` = \'Activo\'
WHERE `usuarios`.`id_usuario` IN (\'27\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `usuarios` SET `nombre_usuario` = \'Tomas\', `password` = \'GRh8eu8M1XAzUkPCvepZbzRJdEhiWjdDamZSWFQ2OEtPbnNtdmc9PQ==\', `tipo_usuario` = \'Taquillero\', `estado_usuario` = \'Activo\'
WHERE `usuarios`.`id_usuario` IN (\'27\')')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `usuarios` SET `nombre_usuario` = \'Tomas\', `password` = \'GRh8eu8M1XAzUkPCvepZbzRJdEhiWjdDamZSWFQ2OEtPbnNtdmc9PQ==\', `tipo_usuario` = \'Taquillero\', `estado_usuario` = \'Activo\'
WHERE `usuarios`.`id_usuario` IN (\'27\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2474): CodeIgniter\Database\BaseConnection->query('UPDATE `usuarios` SET `nombre_usuario` = :nombre_usuario:, `password` = :password:, `tipo_usuario` = :tipo_usuario:, `estado_usuario` = :estado_usuario:
WHERE `usuarios`.`id_usuario` IN :usuarios.id_usuario:', [...], false)
 5 SYSTEMPATH\Model.php(393): CodeIgniter\Database\BaseBuilder->update()
 6 SYSTEMPATH\BaseModel.php(987): CodeIgniter\Model->doUpdate([...], [...])
 7 SYSTEMPATH\Model.php(807): CodeIgniter\BaseModel->update([...], [...])
 8 APPPATH\Controllers\Usuarios.php(211): CodeIgniter\Model->update('27', [...])
 9 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Usuarios->actualizar()
10 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuarios))
11 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-03-07 19:48:20 --> mysqli_sql_exception: Duplicate entry 'Tomas' for key 'unique_nombre_usuario' in C:\laragon\www\cine\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\laragon\www\cine\system\Database\MySQLi\Connection.php(306): mysqli->query('UPDATE `usuario...', 0)
#1 C:\laragon\www\cine\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `usuario...')
#2 C:\laragon\www\cine\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `usuario...')
#3 C:\laragon\www\cine\system\Database\BaseBuilder.php(2474): CodeIgniter\Database\BaseConnection->query('UPDATE `usuario...', Array, false)
#4 C:\laragon\www\cine\system\Model.php(393): CodeIgniter\Database\BaseBuilder->update()
#5 C:\laragon\www\cine\system\BaseModel.php(987): CodeIgniter\Model->doUpdate(Array, Array)
#6 C:\laragon\www\cine\system\Model.php(807): CodeIgniter\BaseModel->update(Array, Array)
#7 C:\laragon\www\cine\app\Controllers\Usuarios.php(211): CodeIgniter\Model->update('27', Array)
#8 C:\laragon\www\cine\system\CodeIgniter.php(941): App\Controllers\Usuarios->actualizar()

#9 C:\laragon\www\cine\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuarios))
#10 C:\laragon\www\cine\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\laragon\www\cine\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 {main}

CRITICAL - 2024-03-07 19:48:20 --> CodeIgniter\Database\Exceptions\DatabaseException: Duplicate entry 'Tomas' for key 'unique_nombre_usuario'
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2474): CodeIgniter\Database\BaseConnection->query('UPDATE `usuarios` SET `nombre_usuario` = :nombre_usuario:, `password` = :password:, `tipo_usuario` = :tipo_usuario:, `estado_usuario` = :estado_usuario:
WHERE `usuarios`.`id_usuario` IN :usuarios.id_usuario:', [...], false)
 2 SYSTEMPATH\Model.php(393): CodeIgniter\Database\BaseBuilder->update()
 3 SYSTEMPATH\BaseModel.php(987): CodeIgniter\Model->doUpdate([...], [...])
 4 SYSTEMPATH\Model.php(807): CodeIgniter\BaseModel->update([...], [...])
 5 APPPATH\Controllers\Usuarios.php(211): CodeIgniter\Model->update('27', [...])
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Usuarios->actualizar()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuarios))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-03-07 19:48:20 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Duplicate entry 'Tomas' for key 'unique_nombre_usuario'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `usuarios` SET `nombre_usuario` = \'Tomas\', `password` = \'VzVkjnSX3nyYgTTPv4btB3hjRi9maFRlTDYza09wYWkrNkUxZWc9PQ==\', `tipo_usuario` = \'Taquillero\', `estado_usuario` = \'Activo\'
WHERE `usuarios`.`id_usuario` IN (\'27\')')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `usuarios` SET `nombre_usuario` = \'Tomas\', `password` = \'VzVkjnSX3nyYgTTPv4btB3hjRi9maFRlTDYza09wYWkrNkUxZWc9PQ==\', `tipo_usuario` = \'Taquillero\', `estado_usuario` = \'Activo\'
WHERE `usuarios`.`id_usuario` IN (\'27\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2474): CodeIgniter\Database\BaseConnection->query('UPDATE `usuarios` SET `nombre_usuario` = :nombre_usuario:, `password` = :password:, `tipo_usuario` = :tipo_usuario:, `estado_usuario` = :estado_usuario:
WHERE `usuarios`.`id_usuario` IN :usuarios.id_usuario:', [...], false)
 4 SYSTEMPATH\Model.php(393): CodeIgniter\Database\BaseBuilder->update()
 5 SYSTEMPATH\BaseModel.php(987): CodeIgniter\Model->doUpdate([...], [...])
 6 SYSTEMPATH\Model.php(807): CodeIgniter\BaseModel->update([...], [...])
 7 APPPATH\Controllers\Usuarios.php(211): CodeIgniter\Model->update('27', [...])
 8 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Usuarios->actualizar()
 9 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuarios))
10 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-03-07 19:48:20 --> [Caused by] mysqli_sql_exception: Duplicate entry 'Tomas' for key 'unique_nombre_usuario'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('UPDATE `usuarios` SET `nombre_usuario` = \'Tomas\', `password` = \'VzVkjnSX3nyYgTTPv4btB3hjRi9maFRlTDYza09wYWkrNkUxZWc9PQ==\', `tipo_usuario` = \'Taquillero\', `estado_usuario` = \'Activo\'
WHERE `usuarios`.`id_usuario` IN (\'27\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `usuarios` SET `nombre_usuario` = \'Tomas\', `password` = \'VzVkjnSX3nyYgTTPv4btB3hjRi9maFRlTDYza09wYWkrNkUxZWc9PQ==\', `tipo_usuario` = \'Taquillero\', `estado_usuario` = \'Activo\'
WHERE `usuarios`.`id_usuario` IN (\'27\')')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `usuarios` SET `nombre_usuario` = \'Tomas\', `password` = \'VzVkjnSX3nyYgTTPv4btB3hjRi9maFRlTDYza09wYWkrNkUxZWc9PQ==\', `tipo_usuario` = \'Taquillero\', `estado_usuario` = \'Activo\'
WHERE `usuarios`.`id_usuario` IN (\'27\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2474): CodeIgniter\Database\BaseConnection->query('UPDATE `usuarios` SET `nombre_usuario` = :nombre_usuario:, `password` = :password:, `tipo_usuario` = :tipo_usuario:, `estado_usuario` = :estado_usuario:
WHERE `usuarios`.`id_usuario` IN :usuarios.id_usuario:', [...], false)
 5 SYSTEMPATH\Model.php(393): CodeIgniter\Database\BaseBuilder->update()
 6 SYSTEMPATH\BaseModel.php(987): CodeIgniter\Model->doUpdate([...], [...])
 7 SYSTEMPATH\Model.php(807): CodeIgniter\BaseModel->update([...], [...])
 8 APPPATH\Controllers\Usuarios.php(211): CodeIgniter\Model->update('27', [...])
 9 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Usuarios->actualizar()
10 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuarios))
11 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-03-07 19:48:24 --> mysqli_sql_exception: Duplicate entry 'Tomas' for key 'unique_nombre_usuario' in C:\laragon\www\cine\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\laragon\www\cine\system\Database\MySQLi\Connection.php(306): mysqli->query('UPDATE `usuario...', 0)
#1 C:\laragon\www\cine\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `usuario...')
#2 C:\laragon\www\cine\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `usuario...')
#3 C:\laragon\www\cine\system\Database\BaseBuilder.php(2474): CodeIgniter\Database\BaseConnection->query('UPDATE `usuario...', Array, false)
#4 C:\laragon\www\cine\system\Model.php(393): CodeIgniter\Database\BaseBuilder->update()
#5 C:\laragon\www\cine\system\BaseModel.php(987): CodeIgniter\Model->doUpdate(Array, Array)
#6 C:\laragon\www\cine\system\Model.php(807): CodeIgniter\BaseModel->update(Array, Array)
#7 C:\laragon\www\cine\app\Controllers\Usuarios.php(211): CodeIgniter\Model->update('27', Array)
#8 C:\laragon\www\cine\system\CodeIgniter.php(941): App\Controllers\Usuarios->actualizar()

#9 C:\laragon\www\cine\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuarios))
#10 C:\laragon\www\cine\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\laragon\www\cine\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 {main}

CRITICAL - 2024-03-07 19:48:24 --> CodeIgniter\Database\Exceptions\DatabaseException: Duplicate entry 'Tomas' for key 'unique_nombre_usuario'
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2474): CodeIgniter\Database\BaseConnection->query('UPDATE `usuarios` SET `nombre_usuario` = :nombre_usuario:, `password` = :password:, `tipo_usuario` = :tipo_usuario:, `estado_usuario` = :estado_usuario:
WHERE `usuarios`.`id_usuario` IN :usuarios.id_usuario:', [...], false)
 2 SYSTEMPATH\Model.php(393): CodeIgniter\Database\BaseBuilder->update()
 3 SYSTEMPATH\BaseModel.php(987): CodeIgniter\Model->doUpdate([...], [...])
 4 SYSTEMPATH\Model.php(807): CodeIgniter\BaseModel->update([...], [...])
 5 APPPATH\Controllers\Usuarios.php(211): CodeIgniter\Model->update('27', [...])
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Usuarios->actualizar()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuarios))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-03-07 19:48:24 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Duplicate entry 'Tomas' for key 'unique_nombre_usuario'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `usuarios` SET `nombre_usuario` = \'Tomas\', `password` = \'PRhu26Vp/Vi5JVaNlxZcAytJWWtxanE5bDMzdzdJV1Jsa0VvaEE9PQ==\', `tipo_usuario` = \'Taquillero\', `estado_usuario` = \'Activo\'
WHERE `usuarios`.`id_usuario` IN (\'27\')')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `usuarios` SET `nombre_usuario` = \'Tomas\', `password` = \'PRhu26Vp/Vi5JVaNlxZcAytJWWtxanE5bDMzdzdJV1Jsa0VvaEE9PQ==\', `tipo_usuario` = \'Taquillero\', `estado_usuario` = \'Activo\'
WHERE `usuarios`.`id_usuario` IN (\'27\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2474): CodeIgniter\Database\BaseConnection->query('UPDATE `usuarios` SET `nombre_usuario` = :nombre_usuario:, `password` = :password:, `tipo_usuario` = :tipo_usuario:, `estado_usuario` = :estado_usuario:
WHERE `usuarios`.`id_usuario` IN :usuarios.id_usuario:', [...], false)
 4 SYSTEMPATH\Model.php(393): CodeIgniter\Database\BaseBuilder->update()
 5 SYSTEMPATH\BaseModel.php(987): CodeIgniter\Model->doUpdate([...], [...])
 6 SYSTEMPATH\Model.php(807): CodeIgniter\BaseModel->update([...], [...])
 7 APPPATH\Controllers\Usuarios.php(211): CodeIgniter\Model->update('27', [...])
 8 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Usuarios->actualizar()
 9 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuarios))
10 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-03-07 19:48:24 --> [Caused by] mysqli_sql_exception: Duplicate entry 'Tomas' for key 'unique_nombre_usuario'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('UPDATE `usuarios` SET `nombre_usuario` = \'Tomas\', `password` = \'PRhu26Vp/Vi5JVaNlxZcAytJWWtxanE5bDMzdzdJV1Jsa0VvaEE9PQ==\', `tipo_usuario` = \'Taquillero\', `estado_usuario` = \'Activo\'
WHERE `usuarios`.`id_usuario` IN (\'27\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `usuarios` SET `nombre_usuario` = \'Tomas\', `password` = \'PRhu26Vp/Vi5JVaNlxZcAytJWWtxanE5bDMzdzdJV1Jsa0VvaEE9PQ==\', `tipo_usuario` = \'Taquillero\', `estado_usuario` = \'Activo\'
WHERE `usuarios`.`id_usuario` IN (\'27\')')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `usuarios` SET `nombre_usuario` = \'Tomas\', `password` = \'PRhu26Vp/Vi5JVaNlxZcAytJWWtxanE5bDMzdzdJV1Jsa0VvaEE9PQ==\', `tipo_usuario` = \'Taquillero\', `estado_usuario` = \'Activo\'
WHERE `usuarios`.`id_usuario` IN (\'27\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2474): CodeIgniter\Database\BaseConnection->query('UPDATE `usuarios` SET `nombre_usuario` = :nombre_usuario:, `password` = :password:, `tipo_usuario` = :tipo_usuario:, `estado_usuario` = :estado_usuario:
WHERE `usuarios`.`id_usuario` IN :usuarios.id_usuario:', [...], false)
 5 SYSTEMPATH\Model.php(393): CodeIgniter\Database\BaseBuilder->update()
 6 SYSTEMPATH\BaseModel.php(987): CodeIgniter\Model->doUpdate([...], [...])
 7 SYSTEMPATH\Model.php(807): CodeIgniter\BaseModel->update([...], [...])
 8 APPPATH\Controllers\Usuarios.php(211): CodeIgniter\Model->update('27', [...])
 9 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Usuarios->actualizar()
10 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuarios))
11 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-03-07 19:48:29 --> mysqli_sql_exception: Duplicate entry 'Tomas' for key 'unique_nombre_usuario' in C:\laragon\www\cine\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\laragon\www\cine\system\Database\MySQLi\Connection.php(306): mysqli->query('UPDATE `usuario...', 0)
#1 C:\laragon\www\cine\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `usuario...')
#2 C:\laragon\www\cine\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `usuario...')
#3 C:\laragon\www\cine\system\Database\BaseBuilder.php(2474): CodeIgniter\Database\BaseConnection->query('UPDATE `usuario...', Array, false)
#4 C:\laragon\www\cine\system\Model.php(393): CodeIgniter\Database\BaseBuilder->update()
#5 C:\laragon\www\cine\system\BaseModel.php(987): CodeIgniter\Model->doUpdate(Array, Array)
#6 C:\laragon\www\cine\system\Model.php(807): CodeIgniter\BaseModel->update(Array, Array)
#7 C:\laragon\www\cine\app\Controllers\Usuarios.php(211): CodeIgniter\Model->update('27', Array)
#8 C:\laragon\www\cine\system\CodeIgniter.php(941): App\Controllers\Usuarios->actualizar()

#9 C:\laragon\www\cine\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuarios))
#10 C:\laragon\www\cine\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\laragon\www\cine\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 {main}

CRITICAL - 2024-03-07 19:48:29 --> CodeIgniter\Database\Exceptions\DatabaseException: Duplicate entry 'Tomas' for key 'unique_nombre_usuario'
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2474): CodeIgniter\Database\BaseConnection->query('UPDATE `usuarios` SET `nombre_usuario` = :nombre_usuario:, `password` = :password:, `tipo_usuario` = :tipo_usuario:, `estado_usuario` = :estado_usuario:
WHERE `usuarios`.`id_usuario` IN :usuarios.id_usuario:', [...], false)
 2 SYSTEMPATH\Model.php(393): CodeIgniter\Database\BaseBuilder->update()
 3 SYSTEMPATH\BaseModel.php(987): CodeIgniter\Model->doUpdate([...], [...])
 4 SYSTEMPATH\Model.php(807): CodeIgniter\BaseModel->update([...], [...])
 5 APPPATH\Controllers\Usuarios.php(211): CodeIgniter\Model->update('27', [...])
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Usuarios->actualizar()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuarios))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-03-07 19:48:29 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Duplicate entry 'Tomas' for key 'unique_nombre_usuario'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `usuarios` SET `nombre_usuario` = \'Tomas\', `password` = \'oQOIiJvp0sHLDHu4sT/R/TVvdjI3QkNqS1k5Zzhhci9qcXRlUVE9PQ==\', `tipo_usuario` = \'Taquillero\', `estado_usuario` = \'Activo\'
WHERE `usuarios`.`id_usuario` IN (\'27\')')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `usuarios` SET `nombre_usuario` = \'Tomas\', `password` = \'oQOIiJvp0sHLDHu4sT/R/TVvdjI3QkNqS1k5Zzhhci9qcXRlUVE9PQ==\', `tipo_usuario` = \'Taquillero\', `estado_usuario` = \'Activo\'
WHERE `usuarios`.`id_usuario` IN (\'27\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2474): CodeIgniter\Database\BaseConnection->query('UPDATE `usuarios` SET `nombre_usuario` = :nombre_usuario:, `password` = :password:, `tipo_usuario` = :tipo_usuario:, `estado_usuario` = :estado_usuario:
WHERE `usuarios`.`id_usuario` IN :usuarios.id_usuario:', [...], false)
 4 SYSTEMPATH\Model.php(393): CodeIgniter\Database\BaseBuilder->update()
 5 SYSTEMPATH\BaseModel.php(987): CodeIgniter\Model->doUpdate([...], [...])
 6 SYSTEMPATH\Model.php(807): CodeIgniter\BaseModel->update([...], [...])
 7 APPPATH\Controllers\Usuarios.php(211): CodeIgniter\Model->update('27', [...])
 8 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Usuarios->actualizar()
 9 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuarios))
10 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-03-07 19:48:29 --> [Caused by] mysqli_sql_exception: Duplicate entry 'Tomas' for key 'unique_nombre_usuario'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('UPDATE `usuarios` SET `nombre_usuario` = \'Tomas\', `password` = \'oQOIiJvp0sHLDHu4sT/R/TVvdjI3QkNqS1k5Zzhhci9qcXRlUVE9PQ==\', `tipo_usuario` = \'Taquillero\', `estado_usuario` = \'Activo\'
WHERE `usuarios`.`id_usuario` IN (\'27\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `usuarios` SET `nombre_usuario` = \'Tomas\', `password` = \'oQOIiJvp0sHLDHu4sT/R/TVvdjI3QkNqS1k5Zzhhci9qcXRlUVE9PQ==\', `tipo_usuario` = \'Taquillero\', `estado_usuario` = \'Activo\'
WHERE `usuarios`.`id_usuario` IN (\'27\')')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `usuarios` SET `nombre_usuario` = \'Tomas\', `password` = \'oQOIiJvp0sHLDHu4sT/R/TVvdjI3QkNqS1k5Zzhhci9qcXRlUVE9PQ==\', `tipo_usuario` = \'Taquillero\', `estado_usuario` = \'Activo\'
WHERE `usuarios`.`id_usuario` IN (\'27\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2474): CodeIgniter\Database\BaseConnection->query('UPDATE `usuarios` SET `nombre_usuario` = :nombre_usuario:, `password` = :password:, `tipo_usuario` = :tipo_usuario:, `estado_usuario` = :estado_usuario:
WHERE `usuarios`.`id_usuario` IN :usuarios.id_usuario:', [...], false)
 5 SYSTEMPATH\Model.php(393): CodeIgniter\Database\BaseBuilder->update()
 6 SYSTEMPATH\BaseModel.php(987): CodeIgniter\Model->doUpdate([...], [...])
 7 SYSTEMPATH\Model.php(807): CodeIgniter\BaseModel->update([...], [...])
 8 APPPATH\Controllers\Usuarios.php(211): CodeIgniter\Model->update('27', [...])
 9 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Usuarios->actualizar()
10 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuarios))
11 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-03-07 22:02:55 --> ErrorException: Attempt to read property "pager" on array
in APPPATH\Controllers\Usuarios.php on line 37.
 1 APPPATH\Controllers\Usuarios.php(37): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read property "pager" on array', 'C:\\laragon\\www\\cine\\app\\Controllers\\Usuarios.php', 37)
 2 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Usuarios->usuarios_view()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuarios))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-03-07 22:03:05 --> ErrorException: Attempt to read property "pager" on array
in APPPATH\Controllers\Usuarios.php on line 37.
 1 APPPATH\Controllers\Usuarios.php(37): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read property "pager" on array', 'C:\\laragon\\www\\cine\\app\\Controllers\\Usuarios.php', 37)
 2 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Usuarios->usuarios_view()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuarios))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-03-07 22:06:27 --> Error: Call to a member function links() on array
in APPPATH\Controllers\Usuarios.php on line 37.
 1 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Usuarios->usuarios_view()
 2 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuarios))
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-03-07 22:06:35 --> Error: Call to a member function links() on array
in APPPATH\Controllers\Usuarios.php on line 37.
 1 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Usuarios->usuarios_view()
 2 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuarios))
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-03-07 22:08:02 --> ErrorException: Attempt to read property "pager" on array
in APPPATH\Controllers\Usuarios.php on line 37.
 1 APPPATH\Controllers\Usuarios.php(37): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read property "pager" on array', 'C:\\laragon\\www\\cine\\app\\Controllers\\Usuarios.php', 37)
 2 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Usuarios->usuarios_view()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuarios))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-03-07 22:19:07 --> Error: Call to undefined method CodeIgniter\Pager\Pager::hasPrevious()
in APPPATH\Views\usuarios\crud_usuarios.php on line 57.

 1 SYSTEMPATH\View\View.php(228): include()
 2 SYSTEMPATH\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 3 SYSTEMPATH\Common.php(1178): CodeIgniter\View\View->render('usuarios/crud_usuarios', [], true)
 4 APPPATH\Controllers\Usuarios.php(38): view('usuarios/crud_usuarios', [...])
 5 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Usuarios->usuarios_view()
 6 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuarios))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()

CRITICAL - 2024-03-07 22:20:55 --> Error: Call to undefined method CodeIgniter\Pager\Pager::hasPrevious()
in APPPATH\Views\usuarios\crud_usuarios.php on line 57.

 1 SYSTEMPATH\View\View.php(228): include()
 2 SYSTEMPATH\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 3 SYSTEMPATH\Common.php(1178): CodeIgniter\View\View->render('usuarios/crud_usuarios', [], true)
 4 APPPATH\Controllers\Usuarios.php(38): view('usuarios/crud_usuarios', [...])
 5 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Usuarios->usuarios_view()
 6 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuarios))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()

CRITICAL - 2024-03-07 22:21:36 --> Error: Call to undefined method CodeIgniter\Pager\Pager::hasPrevious()
in APPPATH\Views\usuarios\crud_usuarios.php on line 57.

 1 SYSTEMPATH\View\View.php(228): include()
 2 SYSTEMPATH\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 3 SYSTEMPATH\Common.php(1178): CodeIgniter\View\View->render('usuarios/crud_usuarios', [], true)
 4 APPPATH\Controllers\Usuarios.php(38): view('usuarios/crud_usuarios', [...])
 5 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Usuarios->usuarios_view()
 6 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuarios))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()

CRITICAL - 2024-03-07 22:23:13 --> ErrorException: Undefined variable $pager
in APPPATH\Views\usuarios\crud_usuarios.php on line 53.
 1 APPPATH\Views\usuarios\crud_usuarios.php(53): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $pager', 'C:\\laragon\\www\\cine\\app\\Views\\usuarios\\crud_usuarios.php', 53)
 2 SYSTEMPATH\View\View.php(228): include('C:\\laragon\\www\\cine\\app\\Views\\usuarios\\crud_usuarios.php')
 3 SYSTEMPATH\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1178): CodeIgniter\View\View->render('usuarios/crud_usuarios', [], true)
 5 APPPATH\Controllers\Usuarios.php(34): view('usuarios/crud_usuarios', [...])

 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Usuarios->usuarios_view()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuarios))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()

CRITICAL - 2024-03-07 22:23:18 --> ErrorException: Undefined variable $pager
in APPPATH\Views\usuarios\crud_usuarios.php on line 53.
 1 APPPATH\Views\usuarios\crud_usuarios.php(53): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $pager', 'C:\\laragon\\www\\cine\\app\\Views\\usuarios\\crud_usuarios.php', 53)
 2 SYSTEMPATH\View\View.php(228): include('C:\\laragon\\www\\cine\\app\\Views\\usuarios\\crud_usuarios.php')
 3 SYSTEMPATH\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1178): CodeIgniter\View\View->render('usuarios/crud_usuarios', [], true)
 5 APPPATH\Controllers\Usuarios.php(34): view('usuarios/crud_usuarios', [...])

 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Usuarios->usuarios_view()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuarios))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()

CRITICAL - 2024-03-07 22:43:49 --> Error: Call to undefined method CodeIgniter\Pager\Pager::hasPrevious()
in APPPATH\Views\usuarios\crud_usuarios.php on line 56.

 1 SYSTEMPATH\View\View.php(228): include()
 2 SYSTEMPATH\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 3 SYSTEMPATH\Common.php(1178): CodeIgniter\View\View->render('usuarios/crud_usuarios', [], true)
 4 APPPATH\Controllers\Usuarios.php(38): view('usuarios/crud_usuarios', [...])
 5 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Usuarios->usuarios_view()
 6 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuarios))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()

CRITICAL - 2024-03-07 22:03:31 --> Error: Call to undefined method CodeIgniter\Pager\Pager::hasPrevious()
in APPPATH\Views\usuarios\crud_usuarios.php on line 57.
 1 SYSTEMPATH\View\View.php(228): include()
 2 SYSTEMPATH\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 3 SYSTEMPATH\Common.php(1178): CodeIgniter\View\View->render('usuarios/crud_usuarios', [], true)
 4 APPPATH\Controllers\Usuarios.php(38): view('usuarios/crud_usuarios', [...])
 5 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Usuarios->usuarios_view()
 6 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuarios))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-03-07 22:03:32 --> Error: Call to undefined method CodeIgniter\Pager\Pager::hasPrevious()
in APPPATH\Views\usuarios\crud_usuarios.php on line 57.
 1 SYSTEMPATH\View\View.php(228): include()
 2 SYSTEMPATH\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 3 SYSTEMPATH\Common.php(1178): CodeIgniter\View\View->render('usuarios/crud_usuarios', [], true)
 4 APPPATH\Controllers\Usuarios.php(38): view('usuarios/crud_usuarios', [...])
 5 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Usuarios->usuarios_view()
 6 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuarios))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-03-07 22:05:01 --> Error: Call to undefined method CodeIgniter\Pager\Pager::hasPrevious()
in APPPATH\Views\usuarios\crud_usuarios.php on line 59.
 1 SYSTEMPATH\View\View.php(228): include()
 2 SYSTEMPATH\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 3 SYSTEMPATH\Common.php(1178): CodeIgniter\View\View->render('usuarios/crud_usuarios', [], true)
 4 APPPATH\Controllers\Usuarios.php(38): view('usuarios/crud_usuarios', [...])
 5 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Usuarios->usuarios_view()
 6 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuarios))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-03-07 22:41:49 --> CodeIgniter\Pager\Exceptions\PagerException: "template_name" is not a valid Pager template.
in SYSTEMPATH\Pager\Pager.php on line 122.
 1 SYSTEMPATH\Pager\Pager.php(122): CodeIgniter\Pager\Exceptions\PagerException::forInvalidTemplate('template_name')
 2 SYSTEMPATH\Pager\Pager.php(112): CodeIgniter\Pager\Pager->displayLinks('default', 'template_name')
 3 APPPATH\Controllers\Usuarios.php(24): CodeIgniter\Pager\Pager->makeLinks(2, 10, 28, 'template_name')
 4 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Usuarios->usuarios_view()
 5 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuarios))
 6 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-03-07 22:42:13 --> ErrorException: Undefined variable $pager_links
in APPPATH\Views\usuarios\crud_usuarios.php on line 54.
 1 APPPATH\Views\usuarios\crud_usuarios.php(54): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $pager_links', 'C:\\laragon\\www\\cine\\app\\Views\\usuarios\\crud_usuarios.php', 54)
 2 SYSTEMPATH\View\View.php(228): include('C:\\laragon\\www\\cine\\app\\Views\\usuarios\\crud_usuarios.php')
 3 SYSTEMPATH\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1178): CodeIgniter\View\View->render('usuarios/crud_usuarios', [], true)
 5 APPPATH\Controllers\Usuarios.php(37): view('usuarios/crud_usuarios', [...])
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Usuarios->usuarios_view()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuarios))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-03-07 22:42:54 --> ErrorException: Undefined variable $pager_links
in APPPATH\Views\usuarios\crud_usuarios.php on line 54.
 1 APPPATH\Views\usuarios\crud_usuarios.php(54): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $pager_links', 'C:\\laragon\\www\\cine\\app\\Views\\usuarios\\crud_usuarios.php', 54)
 2 SYSTEMPATH\View\View.php(228): include('C:\\laragon\\www\\cine\\app\\Views\\usuarios\\crud_usuarios.php')
 3 SYSTEMPATH\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1178): CodeIgniter\View\View->render('usuarios/crud_usuarios', [], true)
 5 APPPATH\Controllers\Usuarios.php(37): view('usuarios/crud_usuarios', [...])
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Usuarios->usuarios_view()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuarios))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-03-07 22:45:57 --> ErrorException: Attempt to read property "pager" on array
in APPPATH\Controllers\Usuarios.php on line 37.
 1 APPPATH\Controllers\Usuarios.php(37): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read property "pager" on array', 'C:\\laragon\\www\\cine\\app\\Controllers\\Usuarios.php', 37)
 2 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Usuarios->usuarios_view()
 3 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuarios))
 4 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
